name: .NET builder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET v5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore .\src\WebApp\WebApp.sln
    - name: Build
      run: dotnet build --no-restore .\src\WebApp\WebApp.sln
    - name: Remove migrations 
      run: rmdir ".\src\WebApp\Migrations" \s
    - name: Test
      run: dotnet test --no-build --verbosity normal .\src\WebApp\WebApp.sln
